database:
  host: "127.0.0.1"
  port: 5432
  username: zero2prod
  password: ""
  database_name: zero2prod

application:
  port: 8000
  host: 127.0.0.1

email_client:
  base_url: "http://localhost"
  sender_email: "test@gmail.com"
  authorisation_token: "my-secret-token"